server:
  port: 8080

spring:
  application:
    name: api-gateway

app:
  jwt:
    secret: ${JWT_SECRET}
    issuer: ${JWT_ISSUER:serviceconnect-auth}

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false

          routes:

            - id: auth-service
              uri: lb://AUTH-SERVICE
              predicates:
                - Path=/api/v1/auth/**

            - id: user-service
              uri: lb://USER-SERVICE
              predicates:
                - Path=/api/v1/users/**

            - id: provider-service
              uri: lb://PROVIDER-SERVICE
              predicates:
                - Path=/api/v1/providers/**

            - id: booking-service
              uri: lb://BOOKING-SERVICE
              predicates:
                - Path=/api/v1/bookings/**

            - id: catalog-service
              uri: lb://CATALOG-SERVICE
              predicates:
                - Path=/api/v1/catalog/**

            - id: review-service
              uri: lb://REVIEW-SERVICE
              predicates:
                - Path=/api/v1/reviews/**

            - id: admin-service
              uri: lb://ADMIN-SERVICE
              predicates:
                - Path=/api/v1/admin/**

    loadbalancer:
      cache:
        enabled: true
        ttl: 35s
        capacity: 256

      retry:
        enabled: true
        max-retries-on-same-service-instance: 0
        max-retries-on-next-service-instance: 1
        retry-on-all-operations: false

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}

    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: health

  endpoint:
    health:
      show-details: never