package com.serviceconnect.booking.entity;

public enum NotificationType {
    // CHAT
    CHAT_MESSAGE,

    // QUOTE
    QUOTE_CREATED,
    QUOTE_ACCEPTED,
    QUOTE_DECLINED,
    QUOTE_EXPIRED,

    // BOOKING
    BOOKING_CREATED,
    BOOKING_ACCEPTED,
    BOOKING_DECLINED,
    BOOKING_CANCELLED,
    BOOKING_STATUS_CHANGED,
    BOOKING_COMPLETED,
    BOOKING_REMINDER,

    // SUPPORT
    SUPPORT_MESSAGE,
    SUPPORT_REPLY,

    // REVIEW
    REVIEW_RECEIVED,
    REVIEW_REMINDER,

    // PROVIDER
    PROVIDER_APPROVED,
    PROVIDER_REJECTED,
    PROVIDER_STATUS_CHANGED,

    // SECURITY
    NEW_LOGIN,
    PASSWORD_CHANGED,
    SECURITY_ALERT
}
