spring:
  application:
    name: auth-service

  profiles:
    active: dev

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8081

app:
  jwt:
    secret: ${JWT_SECRET}
    issuer: serviceconnect-auth
    access-token-expiration: 900000

auth-service:
  url: http://localhost:8081

services:
  user:
    url: http://localhost:8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

brevo:
  api-key: ${BREVO_API_KEY}
  api-url: https://api.brevo.com/v3/smtp/email

  sender:
    name: ServiceConnect
    email: ${BREVO_SENDER_EMAIL}

  sms-api-url: https://api.brevo.com/v3/transactionalSMS/send
  sms-sender: ServiceConnect