server:
  port: 8084

spring:
  application:
    name: provider-service

  cloud:
    loadbalancer:
      cache:
        enabled: true
        ttl: 35s
        capacity: 256
      retry:
        enabled: true
        max-retries-on-same-service-instance: 0
        max-retries-on-next-service-instance: 1
        retry-on-all-operations: false

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  management:
    endpoints:
      web:
        exposure:
          include: health

    endpoint:
      health:
        show-details: never


  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    locations: classpath:db/migration

jwt:
  secret: ${JWT_SECRET}
  issuer: serviceconnect-auth

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true