server:
  port: 8085

spring:
  application:
    name: booking-service

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

management:
  endpoints:
    web:
      exposure:
        include: health,info

  endpoint:
    health:
      show-details: always

jwt:
  secret: ${JWT_SECRET}
  issuer: serviceconnect-auth

provider-service:
  url: http://localhost:8084

services:
  catalog:
    url: http://localhost:8086